Repository BuildForSDG/Team-196-Project, pull requests merged in 2020-05, with the labels that each got.

#7 Adds ER diagram
  docs/erd.png
Labels: assigned, awaiting review

#8 Feature: user authentication
  Gemfile
  Gemfile.lock
  README.md
  app/auth/authenticate_user.rb
  app/auth/authorize_api_request.rb
  app/controllers/application_controller.rb
  app/controllers/authentication_controller.rb
  app/controllers/concerns/exception_handler.rb
  app/controllers/concerns/response.rb
  app/controllers/users_controller.rb
  app/lib/json_web_token.rb
  app/lib/message.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20200512123024_create_users.rb
  db/schema.rb
  spec/auth/authenticate_user_spec.rb
  spec/auth/authorize_api_request_spec.rb
  spec/controller/application_controller_spec.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/authentication_request_spec.rb
  spec/requests/users_request_spec.rb
  spec/spec_helper.rb
  spec/support/controller_spec_helper.rb
  spec/support/request_spec_helper.rb
Labels: awaiting review

#11 feat: added schedule date
  app/controllers/records_controller.rb
  config/routes.rb
  db/migrate/20200531130740_add_schedule_date_to_records.rb
  db/schema.rb
Labels: assigned, enhancement
